fixing dead link in Readme comment
digitalbazaar/pyld pull request #152
Opened 2021-04-13 07:48 UTC by Echsecutor

2023-10-18 13:35 UTC, anatoly-scherbakov requested changes

2023-10-18 13:35 UTC, anatoly-scherbakov commented on README.rst
> +    # (URDNA2015), see: https://json-ld.github.io/rdf-dataset-canonicalization/spec/index.html
```suggestion
    # (URDNA2015), see: https://www.w3.org/TR/rdf-canon/
```

The previous link had already died :skull:

2023-10-19 08:56 UTC, anatoly-scherbakov approved these changes
@Echsecutor thank you!

@davidlehn I believe we can merge this, can we?

2024-02-05 20:13 UTC, BigBlueHat approved these changes

2024-02-05 20:13 UTC, merged