ability to fetch from local ipfs instance
digitalbazaar/pyld pull request #153
Opened 2021-05-14 20:03 UTC by drbh

not sure if this functionality is on the roadmap but reading context's from IPFS are helpful to a personal use case.

Please let me know what you think, and what changes would be needed to add this to the library

Use example
```python
from pyld import jsonld
import json

context = {
  "@context": {
    "name": "http://schema.org/name",
    "image": {
      "@id": "http://schema.org/image",
      "@type": "@id"
    },
    "homepage": {
      "@id": "http://schema.org/url",
      "@type": "@id"
    }
  }
}

import ipfshttpclient
client = ipfshttpclient.connect()
cid = client.add_json(context)

doc = {
  "@context": f"ipfs://{cid}",
  "name": "Manu Sporny",
  "homepage": "http://manu.sporny.org/",
  "image": "http://manu.sporny.org/images/manu.png"
}

compacted = jsonld.compact(doc, context)

# {
#   "@context": {
#     "name": "http://schema.org/name",
#     "image": {
#       "@id": "http://schema.org/image",
#       "@type": "@id"
#     },
#     "homepage": {
#       "@id": "http://schema.org/url",
#       "@type": "@id"
#     }
#   },
#   "image": "http://manu.sporny.org/images/manu.png",
#   "name": "Manu Sporny",
#   "homepage": "http://manu.sporny.org/"
# }
```

2021-07-25 15:28 UTC, anatoly-scherbakov commented
@drbh this might be outdated, but I am also interested in using IPFS with `pyld`. I would believe though that it would be beneficial to create a separate Document Loader for IPFS instead of adding an `if` to existing `requests` based loader. Did you pursue that or a different venue to achieve your goal? Were you successful? Is there any public info about your project?

2023-10-18 13:34 UTC, anatoly-scherbakov requested changes

2023-10-18 13:34 UTC, anatoly-scherbakov commented on lib/pyld/documentloader/requests.py
> +            if pieces.scheme == "ipfs":
As I have already commented earlier, this should probably be refactored to a separate project.

2023-11-01 16:46 UTC, BigBlueHat commented
The jsonld.js library has pluggable document loaders--which looks to be what's actually needed here vs. adding custom loader code directly: https://github.com/digitalbazaar/jsonld.js#custom-document-loader

I'd suggest exploring implementing something like that custom document loader approach and then refactoring this to use that approach for pluggability.

2023-11-01 20:51 UTC, drbh commented
closing since this is a bit outdated and a better impl strategy has been suggested above. Thanks!

2023-11-01 20:51 UTC, closed without merging