load_document: Lower priority of HTML inputs
digitalbazaar/pyld pull request #170
Opened 2022-11-20 09:29 UTC by cid-chan

This fixes a bug with activitypub related documents: The schema "https://www.w3.org/ns/activitystreams" renders the spec if "application/json" has a lower prioritisation than "text/html".

2023-10-18 13:28 UTC, anatoly-scherbakov requested changes

2023-10-18 13:28 UTC, anatoly-scherbakov commented on lib/pyld/jsonld.py
> +        'Accept': 'application/ld+json, application/json;q=0.8'
We define `headers['Accept']` here…

2023-10-18 13:28 UTC, anatoly-scherbakov commented on lib/pyld/jsonld.py
> +    headers['Accept'] = headers['Accept'] + ', text/html;q=0.5, application/xhtml+xml;q=0.5'
…and we modify that value here. 

* Would it be possible to specify the final value right away?
* Probably a comment explaining what the magic `0.5` means would also be helpful to future readers.

2023-11-01 16:49 UTC, BigBlueHat commented
This looks fine generally, but lets get some tests written for it. @anatoly-scherbakov would you be up for doing that to test out the "local tests" you were sad we didn't have here?

2026-01-05 16:44 UTC, mielvds commented
@anatoly-scherbakov if it still makes sense; could you pick this back up? #228 introduces some "local tests" you can extend.

2026-01-19 17:42 UTC, anatoly-scherbakov approved these changes

2026-01-20 09:10 UTC, mielvds approved these changes
Looks good! The only thought I had was about the use of class-based vs function-based tests. OK for merging as is, but I might merge this with another test file in #228 later on.

2026-02-11 09:02 UTC, merged